
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

logging.level.org.springframework=INFO

logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.jwt.issuer=mini-crm